/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import models.CityStore;
import models.CommunityStore;
import models.DoctorStore;
import models.EncounterStore;
import models.HospitalStore;
import models.HouseStore;
import models.PatientStore;
import models.PersonStore;
import models.VitalSignsStore;

/**
 *
 * @author Ravindra
 */
public class DoctorNav extends javax.swing.JPanel {

    /**
     * Creates new form DoctorNav
     */
    javax.swing.JSplitPane SplitPane;
    CityStore cityStore;
    models.SystemAdmin systemAdmin;
    CommunityStore communityStore;
    HospitalStore hospitalStore;
    HouseStore houseStore;
    DoctorStore doctorStore;
    PersonStore personStore;
    EncounterStore encounterStore;
    VitalSignsStore vitalSignsStore;
    PatientStore patientStore;
    
    public DoctorNav(javax.swing.JSplitPane SplitPane, 
        models.SystemAdmin systemAdmin,
        CityStore cityStore,
        CommunityStore communityStore,
        HospitalStore hospitalStore,
        HouseStore houseStore,
        DoctorStore doctorStore,
        PersonStore personStore,
        EncounterStore encounterStore,
        VitalSignsStore vitalSignsStore,
        PatientStore patientStore) {
        
        
        initComponents();
        this.SplitPane = SplitPane;
        this.cityStore = cityStore;
        this.systemAdmin = systemAdmin;
        this.communityStore = communityStore;
        this.hospitalStore = hospitalStore;
        this.houseStore = houseStore;
        this.doctorStore = doctorStore;
        this.personStore = personStore;
        this.encounterStore = encounterStore;
        this.vitalSignsStore = vitalSignsStore;
        this.patientStore = patientStore;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnCreateVital = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setText("Hello,");

        lblName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblName.setText("Doctor");

        btnCreateVital.setBackground(new java.awt.Color(153, 0, 153));
        btnCreateVital.setText("Encounter");
        btnCreateVital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateVitalActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setText("logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateVital)
                            .addComponent(jLabel3)
                            .addComponent(btnLogout))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addGap(18, 18, 18)
                .addComponent(btnCreateVital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateVitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateVitalActionPerformed
        
        if(vitalSignsStore.getStore() == null) {
            JOptionPane.showMessageDialog(this,"No vitals found");
        }
        DoctorEncountPanel doctorEncountPanel = new DoctorEncountPanel(systemAdmin, vitalSignsStore, doctorStore, hospitalStore, encounterStore);
        SplitPane.setRightComponent(doctorEncountPanel);
    }//GEN-LAST:event_btnCreateVitalActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginPanel loginPanel = new LoginPanel(SplitPane, systemAdmin,cityStore, communityStore, hospitalStore, houseStore, doctorStore, personStore, encounterStore, vitalSignsStore, patientStore);
        SplitPane.setRightComponent(loginPanel);
        SplitPane.setLeftComponent(null);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateVital;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
