/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import models.Doctor;
import models.DoctorStore;
import models.HospitalStore;

/**
 *
 * @author Ravindra
 */
public class DoctorCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorCreatePanel
     */
    DoctorStore doctorStore;
    HospitalStore hospitalStore; 
    public DoctorCreatePanel(DoctorStore doctorStore, HospitalStore hospitalStore) {
        initComponents();
        
        this.doctorStore = doctorStore;
        this.hospitalStore = hospitalStore;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextDoctorId = new javax.swing.JTextField();
        TextDoctorFirstName = new javax.swing.JTextField();
        TextDoctorLastName = new javax.swing.JTextField();
        TextDoctorDOB = new javax.swing.JTextField();
        TextDoctorEmail = new javax.swing.JTextField();
        TextDoctorPhoneNumber = new javax.swing.JTextField();
        TextDoctorAddress = new javax.swing.JTextField();
        TextHospitalId = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        TextPassword = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Doctor Panel");

        jLabel2.setText("Doctor ID");

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Gender");

        jLabel6.setText("Date of Birth");

        jLabel7.setText("Email");

        jLabel8.setText("Phone Number");

        jLabel9.setText("Address");

        jLabel10.setText("Hospital ID");

        TextDoctorFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextDoctorFirstNameKeyPressed(evt);
            }
        });

        TextDoctorLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextDoctorLastNameKeyPressed(evt);
            }
        });

        TextDoctorPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextDoctorPhoneNumberKeyReleased(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel11.setText("Password");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(TextPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextDoctorId, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(TextDoctorFirstName)
                            .addComponent(TextDoctorLastName)
                            .addComponent(TextDoctorDOB)
                            .addComponent(TextDoctorEmail)
                            .addComponent(TextDoctorPhoneNumber)
                            .addComponent(TextDoctorAddress)
                            .addComponent(TextHospitalId)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDoctorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDoctorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDoctorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDoctorDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDoctorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDoctorPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDoctorAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextHospitalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        Doctor resource = doctorStore.addNewResource();
        
        resource.setDid(Integer.parseInt(TextDoctorId.getText()));
        resource.setHospitalId(Integer.parseInt(TextHospitalId.getText()));
        
        resource.setAddress(TextDoctorAddress.getText());
        resource.setDOB(TextDoctorDOB.getText());
        resource.setEmail(TextDoctorEmail.getText());
        resource.setFirstName(TextDoctorFirstName.getText());
        resource.setLastName(TextDoctorLastName.getText());
        resource.setGender(jComboBox1.getSelectedItem().toString());
        resource.setPhone(TextDoctorPhoneNumber.getText());
        resource.setPassword(TextPassword.getText());
        
        
        
        String Email;
        
        
        if(TextDoctorEmail.getText().contains("@") && TextDoctorEmail.getText().endsWith(".com")){
                Email = TextDoctorEmail.getText();
             }
             else{
                 JOptionPane.showMessageDialog(null, "Invalid Email");
            return;
}
        
        
        
        JOptionPane.showMessageDialog(this,"Successfully added");
        
        TextDoctorId.setText("");
        TextHospitalId.setText("");
        TextDoctorAddress.setText("");
        TextDoctorDOB.setText("");
        TextDoctorEmail.setText("");
        TextDoctorFirstName.setText("");
        TextDoctorLastName.setText("");
        //jComboBox1.setText("");
        TextDoctorPhoneNumber.setText("");
        TextPassword.setText("");
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void TextDoctorPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDoctorPhoneNumberKeyReleased
        // TODO add your handling code here:
        
        String PhoneNum = TextDoctorPhoneNumber.getText();
        int len  = PhoneNum.length();
        char h = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(len<10)
            {
                TextDoctorPhoneNumber.setEditable(true);
            }
            else
            {
                TextDoctorPhoneNumber.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
             {
                TextDoctorPhoneNumber.setEditable(true);
            }
            else
            {
                TextDoctorPhoneNumber.setEditable(false);
            }
        }
        if(PhoneNum.matches("^[0-9]*$") && PhoneNum.length()==9)
        {
            TextDoctorPhoneNumber.setBackground(Color.GREEN);
          
        }
        else
              TextDoctorPhoneNumber.setBackground(Color.red);
    
    }//GEN-LAST:event_TextDoctorPhoneNumberKeyReleased

    private void TextDoctorFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDoctorFirstNameKeyPressed
        // TODO add your handling code here:
        char C = evt.getKeyChar();
        if (Character.isLetter(C)|| Character.isWhitespace(C) || Character.isISOControl(C)){
        
            TextDoctorFirstName.setEditable(true);
        
        }
        
        else{
        
            TextDoctorFirstName.setEditable(true);
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Name");
  
}
    }//GEN-LAST:event_TextDoctorFirstNameKeyPressed

    private void TextDoctorLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDoctorLastNameKeyPressed
        // TODO add your handling code here:
        char C = evt.getKeyChar();
        if (Character.isLetter(C)|| Character.isWhitespace(C) || Character.isISOControl(C)){
        
            TextDoctorLastName.setEditable(true);
        
        }
        
        else{
        
            TextDoctorLastName.setEditable(true);
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Name");
  
}
        
    }//GEN-LAST:event_TextDoctorLastNameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextDoctorAddress;
    private javax.swing.JTextField TextDoctorDOB;
    private javax.swing.JTextField TextDoctorEmail;
    private javax.swing.JTextField TextDoctorFirstName;
    private javax.swing.JTextField TextDoctorId;
    private javax.swing.JTextField TextDoctorLastName;
    private javax.swing.JTextField TextDoctorPhoneNumber;
    private javax.swing.JTextField TextHospitalId;
    private javax.swing.JPasswordField TextPassword;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
