/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;

/**
 *
 * @author Ravindra
 */
public class filldetails extends javax.swing.JPanel {
    private JPanel rightpanel;

    /**
     * Creates new form create_person
     */
    public filldetails(JPanel rightpanel) {
        initComponents();
        this.rightpanel=rightpanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        labelname = new javax.swing.JLabel();
        labelage = new javax.swing.JLabel();
        labelweight = new javax.swing.JLabel();
        labeladdress = new javax.swing.JLabel();
        labelcommunity = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtweight = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        btnback1 = new javax.swing.JButton();
        labelhospital = new javax.swing.JLabel();
        labeldr = new javax.swing.JLabel();
        txtlocality = new javax.swing.JComboBox<>();
        txthospital = new javax.swing.JComboBox<>();
        txtdr = new javax.swing.JComboBox<>();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("PERSON PROFILE-");

        labelname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelname.setText("NAME :");

        labelage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelage.setText("AGE :");

        labelweight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelweight.setText("WEIGHT :");

        labeladdress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labeladdress.setText("ADDRESS :");

        labelcommunity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelcommunity.setText("COMMUNITY :");

        btnsave.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtweightActionPerformed(evt);
            }
        });

        btnback1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnback1.setText("<< BACK");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        labelhospital.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelhospital.setText("Hospital :");

        labeldr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labeldr.setText("Dr");

        txtlocality.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtlocality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Locality", "Westland", "Longwood", "Brookline" }));
        txtlocality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlocalityActionPerformed(evt);
            }
        });

        txthospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthospitalActionPerformed(evt);
            }
        });

        txtdr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtdr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor", "Dentist", "Cardiologist", "Occupational Therapist" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labeladdress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelweight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelcommunity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelhospital)
                    .addComponent(labeldr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnback1)
                        .addGap(18, 18, 18)
                        .addComponent(btnsave)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtaddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtweight, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtage, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlocality, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txthospital, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdr, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE))
                        .addGap(179, 179, 179))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelweight)
                    .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeladdress)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcommunity)
                    .addComponent(txtlocality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelhospital)
                    .addComponent(txthospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeldr)
                    .addComponent(txtdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnback1))
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtweightActionPerformed

    private void txtlocalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocalityActionPerformed
        // TODO add your handling code here:
        if(txtlocality.getSelectedItem().equals("Westland")){
            txthospital.removeAllItems();

            txthospital.addItem("Boston Medical Center");
            txthospital.addItem("Brigham and Women's Hospital");
            txthospital.addItem("Massachusetts General Hospital");

        }

        else{
            if(txtlocality.getSelectedItem().equals("Longwood")){
                txthospital.removeAllItems();

                txthospital.addItem("Boston children's Hospital");
                txthospital.addItem("Emergency Department");
                txthospital.addItem("General Hospital");
            }
            else{
                txthospital.removeAllItems();
                //txtHospital.addItem(null);
                txthospital.addItem("HRI Hospital");
                txthospital.addItem("Bournewood Hospital");
                txthospital.addItem("Lemuel Shattuck Hospital");
            }
        }
    }//GEN-LAST:event_txtlocalityActionPerformed

    private void txthospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthospitalActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
         rightpanel.remove(this);
        CardLayout layout = (CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
    }//GEN-LAST:event_btnback1ActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback1;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labeladdress;
    private javax.swing.JLabel labelage;
    private javax.swing.JLabel labelcommunity;
    private javax.swing.JLabel labeldr;
    private javax.swing.JLabel labelhospital;
    private javax.swing.JLabel labelname;
    private javax.swing.JLabel labelweight;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JComboBox<String> txtdr;
    private javax.swing.JComboBox<String> txthospital;
    private javax.swing.JComboBox<String> txtlocality;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
