/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import models.CityStore;
import models.Community;
import models.CommunityStore;
import models.DoctorStore;
import models.EncounterStore;
import models.HospitalStore;
import models.HouseStore;
import models.PatientStore;
import models.PersonStore;
import models.VitalSignsStore;

/**
 *
 * @author Ravindra
 */
public class Navigation extends javax.swing.JPanel {

    /**
     * Creates new form Navigation
     */
    
    javax.swing.JSplitPane SplitPane;
    CityStore cityStore;
    models.SystemAdmin systemAdmin;
    CommunityStore communityStore;
    HospitalStore hospitalStore;
    HouseStore houseStore;
    DoctorStore doctorStore;
    PersonStore personStore;
    EncounterStore encounterStore;
    VitalSignsStore vitalSignsStore;
    PatientStore patientStore;
    
    public Navigation(javax.swing.JSplitPane SplitPane,
        models.SystemAdmin systemAdmin,
        CityStore cityStore,
        CommunityStore communityStore,
        HospitalStore hospitalStore,
        HouseStore houseStore,
        DoctorStore doctorStore,
        PersonStore personStore,
        EncounterStore encounterStore,
        VitalSignsStore vitalSignsStore,
        PatientStore patientStore) {
        
        initComponents();
        this.SplitPane = SplitPane;
        this.cityStore = cityStore;
        this.systemAdmin = systemAdmin;
        this.communityStore = communityStore;
        this.hospitalStore = hospitalStore;
        this.houseStore = houseStore;
        this.doctorStore = doctorStore;
        this.personStore = personStore;
        this.encounterStore = encounterStore;
        this.vitalSignsStore = vitalSignsStore;
        this.patientStore = patientStore;
        
        initCombos();
        
    }
    
    private void initCombos() {
        
       if("Community Admin".matches(systemAdmin.getCurrentUser())) {
           hideCity();
       }
       
       if("Hospital Admin".matches(systemAdmin.getCurrentUser())) {
           hideCity();
           hideCommunity();
           hideHouseAndPerson();
       }
    }
    
    private void hideHouseAndPerson() {
        btnPersonCreate.hide();
        btnPersonView.hide();
        lblPerson.hide();
        
        btnHouseCreate.hide();
        btnHouseView.hide();
        lblHouse.hide();
        
       
    }
    
    private void hideCommunity() {
        btnComtCreate.hide();
        btnComtView.hide();
        lblCommunity.hide();
       
    }
    
    private void hideCity() {
        btnCreateCity.hide();
        btnViewCity.hide();
        lblCity.hide();
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnCreateCity = new javax.swing.JButton();
        btnViewCity = new javax.swing.JButton();
        lblCity = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        btnComtCreate = new javax.swing.JButton();
        btnComtView = new javax.swing.JButton();
        lblHospital = new javax.swing.JLabel();
        btnHospCreate = new javax.swing.JButton();
        btnHospView = new javax.swing.JButton();
        lblHouse = new javax.swing.JLabel();
        btnHouseCreate = new javax.swing.JButton();
        btnHouseView = new javax.swing.JButton();
        lblDoctor = new javax.swing.JLabel();
        btnDoctorCreate = new javax.swing.JButton();
        btnDoctorView = new javax.swing.JButton();
        lblPerson = new javax.swing.JLabel();
        btnPersonCreate = new javax.swing.JButton();
        btnPersonView = new javax.swing.JButton();
        lblVitalSigns = new javax.swing.JLabel();
        btnVitalCreate = new javax.swing.JButton();
        btnVitalView = new javax.swing.JButton();
        lblEncounters = new javax.swing.JLabel();
        btnEncountCreate = new javax.swing.JButton();
        btnEncountView = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));

        btnLogout.setText(" logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnCreateCity.setBackground(new java.awt.Color(51, 255, 51));
        btnCreateCity.setText("Create");
        btnCreateCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateCityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateCityMouseExited(evt);
            }
        });
        btnCreateCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCityActionPerformed(evt);
            }
        });

        btnViewCity.setBackground(new java.awt.Color(51, 204, 0));
        btnViewCity.setText("View");
        btnViewCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewCityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewCityMouseExited(evt);
            }
        });
        btnViewCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCityActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCity.setText("City");

        lblCommunity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCommunity.setText("Community");

        btnComtCreate.setBackground(new java.awt.Color(51, 255, 51));
        btnComtCreate.setText("Create");
        btnComtCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComtCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComtCreateMouseExited(evt);
            }
        });
        btnComtCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComtCreateActionPerformed(evt);
            }
        });

        btnComtView.setBackground(new java.awt.Color(51, 204, 0));
        btnComtView.setText("View");
        btnComtView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComtViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComtViewMouseExited(evt);
            }
        });
        btnComtView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComtViewActionPerformed(evt);
            }
        });

        lblHospital.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHospital.setText("Hospital");

        btnHospCreate.setBackground(new java.awt.Color(51, 255, 51));
        btnHospCreate.setText("Create");
        btnHospCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHospCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHospCreateMouseExited(evt);
            }
        });
        btnHospCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospCreateActionPerformed(evt);
            }
        });

        btnHospView.setBackground(new java.awt.Color(51, 204, 0));
        btnHospView.setText("View");
        btnHospView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHospViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHospViewMouseExited(evt);
            }
        });
        btnHospView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospViewActionPerformed(evt);
            }
        });

        lblHouse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHouse.setText("House");

        btnHouseCreate.setBackground(new java.awt.Color(51, 255, 51));
        btnHouseCreate.setText("Create");
        btnHouseCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHouseCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHouseCreateMouseExited(evt);
            }
        });
        btnHouseCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHouseCreateActionPerformed(evt);
            }
        });

        btnHouseView.setBackground(new java.awt.Color(51, 204, 0));
        btnHouseView.setText("View");
        btnHouseView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHouseViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHouseViewMouseExited(evt);
            }
        });
        btnHouseView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHouseViewActionPerformed(evt);
            }
        });

        lblDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDoctor.setText("Doctor");

        btnDoctorCreate.setBackground(new java.awt.Color(51, 255, 51));
        btnDoctorCreate.setText("Create");
        btnDoctorCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoctorCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoctorCreateMouseExited(evt);
            }
        });
        btnDoctorCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorCreateActionPerformed(evt);
            }
        });

        btnDoctorView.setBackground(new java.awt.Color(51, 204, 0));
        btnDoctorView.setText("View");
        btnDoctorView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoctorViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoctorViewMouseExited(evt);
            }
        });
        btnDoctorView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorViewActionPerformed(evt);
            }
        });

        lblPerson.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPerson.setText("Person");

        btnPersonCreate.setBackground(new java.awt.Color(51, 255, 0));
        btnPersonCreate.setText("Create");
        btnPersonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonCreateMouseExited(evt);
            }
        });
        btnPersonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonCreateActionPerformed(evt);
            }
        });

        btnPersonView.setBackground(new java.awt.Color(51, 204, 0));
        btnPersonView.setText("View");
        btnPersonView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonViewMouseExited(evt);
            }
        });
        btnPersonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonViewActionPerformed(evt);
            }
        });

        lblVitalSigns.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVitalSigns.setText("Vital Signs");

        btnVitalCreate.setBackground(new java.awt.Color(51, 255, 51));
        btnVitalCreate.setText("Create");
        btnVitalCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVitalCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVitalCreateMouseExited(evt);
            }
        });
        btnVitalCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitalCreateActionPerformed(evt);
            }
        });

        btnVitalView.setBackground(new java.awt.Color(51, 204, 0));
        btnVitalView.setText("View");
        btnVitalView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVitalViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVitalViewMouseExited(evt);
            }
        });
        btnVitalView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitalViewActionPerformed(evt);
            }
        });

        lblEncounters.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEncounters.setText("Encounters");

        btnEncountCreate.setBackground(new java.awt.Color(51, 255, 51));
        btnEncountCreate.setText("Create");
        btnEncountCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEncountCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEncountCreateMouseExited(evt);
            }
        });
        btnEncountCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncountCreateActionPerformed(evt);
            }
        });

        btnEncountView.setBackground(new java.awt.Color(51, 204, 0));
        btnEncountView.setText("View");
        btnEncountView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEncountViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEncountViewMouseExited(evt);
            }
        });
        btnEncountView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncountViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLogout)
                                    .addComponent(btnCreateCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(lblCity)
                                .addComponent(lblHospital)
                                .addComponent(btnHospCreate)
                                .addComponent(btnHospView)
                                .addComponent(lblHouse))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPerson)
                                .addComponent(lblCommunity)
                                .addComponent(btnComtCreate)
                                .addComponent(btnComtView)
                                .addComponent(lblDoctor)
                                .addComponent(btnDoctorCreate)
                                .addComponent(btnDoctorView)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnHouseCreate)
                                .addComponent(btnHouseView))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPersonCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnPersonView)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addComponent(lblVitalSigns)
                    .addComponent(btnVitalCreate)
                    .addComponent(btnVitalView)
                    .addComponent(lblEncounters)
                    .addComponent(btnEncountCreate)
                    .addComponent(btnEncountView))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewCity))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCommunity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComtCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComtView)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHospital)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHospCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHospView))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDoctorCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDoctorView)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouse)
                    .addComponent(lblPerson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHouseCreate)
                    .addComponent(btnPersonCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHouseView)
                    .addComponent(btnPersonView))
                .addGap(30, 30, 30)
                .addComponent(lblVitalSigns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVitalCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVitalView)
                .addGap(18, 18, 18)
                .addComponent(lblEncounters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEncountCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEncountView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
        LoginPanel loginPanel = new LoginPanel(SplitPane, systemAdmin,cityStore, communityStore, hospitalStore, houseStore, doctorStore, personStore, encounterStore, vitalSignsStore, patientStore);
        SplitPane.setRightComponent(loginPanel);
        SplitPane.setLeftComponent(null);
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCreateCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCityActionPerformed
        CityCreatePanel cityCreatePanel = new CityCreatePanel(cityStore);
        SplitPane.setRightComponent(cityCreatePanel);
    }//GEN-LAST:event_btnCreateCityActionPerformed

    private void btnViewCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCityActionPerformed
        CityViewPanel cityViewPanel =  new CityViewPanel(cityStore);
        SplitPane.setRightComponent(cityViewPanel);
    }//GEN-LAST:event_btnViewCityActionPerformed

    private void btnComtCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComtCreateActionPerformed
        CommunityCreatePanel communityCreatePanel =  new CommunityCreatePanel(cityStore, communityStore);
        SplitPane.setRightComponent(communityCreatePanel);
    }//GEN-LAST:event_btnComtCreateActionPerformed

    private void btnComtViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComtViewActionPerformed
        CommunityViewPanel communityViewPanel =  new CommunityViewPanel(cityStore, communityStore, systemAdmin);
        SplitPane.setRightComponent(communityViewPanel);
    }//GEN-LAST:event_btnComtViewActionPerformed

    private void btnHospCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospCreateActionPerformed
        HospCreatePanel hospCreatePanel = new HospCreatePanel(hospitalStore, communityStore);
        SplitPane.setRightComponent(hospCreatePanel);
    }//GEN-LAST:event_btnHospCreateActionPerformed

    private void btnHospViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospViewActionPerformed
       HospViewPanel hospViewPanel = new HospViewPanel(hospitalStore, communityStore, systemAdmin);
       SplitPane.setRightComponent(hospViewPanel);
    }//GEN-LAST:event_btnHospViewActionPerformed

    private void btnHouseCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHouseCreateActionPerformed
       HouseCreatePanel houseCreatPanel = new HouseCreatePanel(houseStore, communityStore);
       SplitPane.setRightComponent(houseCreatPanel);
    }//GEN-LAST:event_btnHouseCreateActionPerformed

    private void btnHouseViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHouseViewActionPerformed
       HouseViewPanel houseViewPanel = new HouseViewPanel(houseStore, communityStore);
       SplitPane.setRightComponent(houseViewPanel);
    }//GEN-LAST:event_btnHouseViewActionPerformed

    private void btnDoctorCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorCreateActionPerformed
        DoctorCreatePanel doctorCreatePanel = new DoctorCreatePanel(doctorStore, hospitalStore);
        SplitPane.setRightComponent(doctorCreatePanel);
    }//GEN-LAST:event_btnDoctorCreateActionPerformed

    private void btnDoctorViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorViewActionPerformed
        DoctorViewPanel doctorViewPanel = new DoctorViewPanel(doctorStore, hospitalStore, systemAdmin);
        SplitPane.setRightComponent(doctorViewPanel);
    }//GEN-LAST:event_btnDoctorViewActionPerformed

    private void btnPersonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonCreateActionPerformed
        PersonCreatePanel personCreatePanel = new PersonCreatePanel(personStore, houseStore, systemAdmin, communityStore);
        SplitPane.setRightComponent(personCreatePanel);
    }//GEN-LAST:event_btnPersonCreateActionPerformed

    private void btnPersonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonViewActionPerformed
        PersonViewPanel personViewPanel = new PersonViewPanel(personStore, houseStore, systemAdmin);
        SplitPane.setRightComponent(personViewPanel);
    }//GEN-LAST:event_btnPersonViewActionPerformed

    private void btnVitalCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitalCreateActionPerformed
        VitalSignsCreatePanel vitalCreatePanel = new VitalSignsCreatePanel(vitalSignsStore, doctorStore, hospitalStore, personStore, patientStore, systemAdmin,communityStore);
        SplitPane.setRightComponent(vitalCreatePanel);
    }//GEN-LAST:event_btnVitalCreateActionPerformed

    private void btnVitalViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitalViewActionPerformed
        VitalSignsViewPanel vitalViewPanel = new VitalSignsViewPanel(vitalSignsStore, doctorStore, hospitalStore, systemAdmin);
        SplitPane.setRightComponent(vitalViewPanel);
    }//GEN-LAST:event_btnVitalViewActionPerformed

    private void btnEncountCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncountCreateActionPerformed
        EncounterCreatePanel encounterCreatePanel = new EncounterCreatePanel(encounterStore, doctorStore);
        SplitPane.setRightComponent(encounterCreatePanel);
    }//GEN-LAST:event_btnEncountCreateActionPerformed

    private void btnEncountViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncountViewActionPerformed
        EncounterViewPanel encounterViewPanel = new EncounterViewPanel(encounterStore, doctorStore);
        SplitPane.setRightComponent(encounterViewPanel);
    }//GEN-LAST:event_btnEncountViewActionPerformed

    private void btnCreateCityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateCityMouseEntered
        // TODO add your handling code here:
        btnCreateCity.setForeground(Color.blue);
    }//GEN-LAST:event_btnCreateCityMouseEntered

    private void btnCreateCityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateCityMouseExited
        // TODO add your handling code here:
        btnCreateCity.setForeground(Color.pink);
    }//GEN-LAST:event_btnCreateCityMouseExited

    private void btnViewCityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewCityMouseEntered
        // TODO add your handling code here:
        btnViewCity.setForeground(Color.blue);
    }//GEN-LAST:event_btnViewCityMouseEntered

    private void btnViewCityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewCityMouseExited
        // TODO add your handling code here:
        btnViewCity.setForeground(Color.black);
    }//GEN-LAST:event_btnViewCityMouseExited

    private void btnComtCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComtCreateMouseEntered
        // TODO add your handling code here:
        btnComtCreate.setForeground(Color.blue);
    }//GEN-LAST:event_btnComtCreateMouseEntered

    private void btnComtCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComtCreateMouseExited
        // TODO add your handling code here:
        btnComtCreate.setForeground(Color.black);
    }//GEN-LAST:event_btnComtCreateMouseExited

    private void btnComtViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComtViewMouseEntered
        // TODO add your handling code here:
        btnComtView.setForeground(Color.blue);
    }//GEN-LAST:event_btnComtViewMouseEntered

    private void btnComtViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComtViewMouseExited
        // TODO add your handling code here:
        btnComtView.setForeground(Color.black);
    }//GEN-LAST:event_btnComtViewMouseExited

    private void btnHospCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHospCreateMouseEntered
        // TODO add your handling code here:
        btnHospCreate.setForeground(Color.blue);
    }//GEN-LAST:event_btnHospCreateMouseEntered

    private void btnHospCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHospCreateMouseExited
        // TODO add your handling code here:
        btnHospCreate.setForeground(Color.black);
    }//GEN-LAST:event_btnHospCreateMouseExited

    private void btnHospViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHospViewMouseEntered
        // TODO add your handling code here:
        btnHospView.setForeground(Color.blue);
    }//GEN-LAST:event_btnHospViewMouseEntered

    private void btnHospViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHospViewMouseExited
        // TODO add your handling code here:
        btnHospView.setForeground(Color.black);
    }//GEN-LAST:event_btnHospViewMouseExited

    private void btnDoctorCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorCreateMouseEntered
        // TODO add your handling code here:
        btnDoctorCreate.setForeground(Color.blue);
    }//GEN-LAST:event_btnDoctorCreateMouseEntered

    private void btnDoctorCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorCreateMouseExited
        // TODO add your handling code here:
        btnDoctorCreate.setForeground(Color.black);
    }//GEN-LAST:event_btnDoctorCreateMouseExited

    private void btnDoctorViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorViewMouseEntered
        // TODO add your handling code here:
        btnDoctorView.setForeground(Color.blue);
    }//GEN-LAST:event_btnDoctorViewMouseEntered

    private void btnDoctorViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorViewMouseExited
        // TODO add your handling code here:
        btnDoctorView.setForeground(Color.black);
    }//GEN-LAST:event_btnDoctorViewMouseExited

    private void btnHouseCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHouseCreateMouseExited
        // TODO add your handling code here:
        btnHouseCreate.setForeground(Color.blue);
    }//GEN-LAST:event_btnHouseCreateMouseExited

    private void btnHouseCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHouseCreateMouseEntered
        // TODO add your handling code here:
        btnHouseCreate.setForeground(Color.black);
    }//GEN-LAST:event_btnHouseCreateMouseEntered

    private void btnHouseViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHouseViewMouseExited
        // TODO add your handling code here:
        btnHouseView.setForeground(Color.blue);
    }//GEN-LAST:event_btnHouseViewMouseExited

    private void btnHouseViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHouseViewMouseEntered
        // TODO add your handling code here:
        btnHouseView.setForeground(Color.black);
    }//GEN-LAST:event_btnHouseViewMouseEntered

    private void btnPersonCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonCreateMouseExited
        // TODO add your handling code here:
        btnPersonCreate.setForeground(Color.blue);
    }//GEN-LAST:event_btnPersonCreateMouseExited

    private void btnPersonCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonCreateMouseEntered
        // TODO add your handling code here:
        btnPersonCreate.setForeground(Color.black);
    }//GEN-LAST:event_btnPersonCreateMouseEntered

    private void btnPersonViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonViewMouseExited
        // TODO add your handling code here:
        btnPersonView.setForeground(Color.blue);
    }//GEN-LAST:event_btnPersonViewMouseExited

    private void btnPersonViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonViewMouseEntered
        // TODO add your handling code here:
        btnPersonView.setForeground(Color.black);
    }//GEN-LAST:event_btnPersonViewMouseEntered

    private void btnVitalCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVitalCreateMouseEntered
        // TODO add your handling code here:
        btnVitalCreate.setForeground(Color.blue);
    }//GEN-LAST:event_btnVitalCreateMouseEntered

    private void btnVitalCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVitalCreateMouseExited
        // TODO add your handling code here:
        btnVitalCreate.setForeground(Color.black);
    }//GEN-LAST:event_btnVitalCreateMouseExited

    private void btnVitalViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVitalViewMouseEntered
        // TODO add your handling code here:
        btnVitalView.setForeground(Color.blue);
    }//GEN-LAST:event_btnVitalViewMouseEntered

    private void btnVitalViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVitalViewMouseExited
        // TODO add your handling code here:
        btnVitalView.setForeground(Color.black);
    }//GEN-LAST:event_btnVitalViewMouseExited

    private void btnEncountCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncountCreateMouseEntered
        // TODO add your handling code here:
        btnEncountCreate.setForeground(Color.blue);
    }//GEN-LAST:event_btnEncountCreateMouseEntered

    private void btnEncountCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncountCreateMouseExited
        // TODO add your handling code here:
        
        btnEncountCreate.setForeground(Color.black);
    }//GEN-LAST:event_btnEncountCreateMouseExited

    private void btnEncountViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncountViewMouseExited
        // TODO add your handling code here:
        btnEncountView.setForeground(Color.blue);
    }//GEN-LAST:event_btnEncountViewMouseExited

    private void btnEncountViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncountViewMouseEntered
        // TODO add your handling code here:
        btnEncountView.setForeground(Color.blue);
    }//GEN-LAST:event_btnEncountViewMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setForeground(Color.blue);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setForeground(Color.red);
    }//GEN-LAST:event_btnLogoutMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComtCreate;
    private javax.swing.JButton btnComtView;
    private javax.swing.JButton btnCreateCity;
    private javax.swing.JButton btnDoctorCreate;
    private javax.swing.JButton btnDoctorView;
    private javax.swing.JButton btnEncountCreate;
    private javax.swing.JButton btnEncountView;
    private javax.swing.JButton btnHospCreate;
    private javax.swing.JButton btnHospView;
    private javax.swing.JButton btnHouseCreate;
    private javax.swing.JButton btnHouseView;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPersonCreate;
    private javax.swing.JButton btnPersonView;
    private javax.swing.JButton btnViewCity;
    private javax.swing.JButton btnVitalCreate;
    private javax.swing.JButton btnVitalView;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblEncounters;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblPerson;
    private javax.swing.JLabel lblVitalSigns;
    // End of variables declaration//GEN-END:variables
}
