/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Community;
import models.CommunityStore;
import models.HouseStore;
import models.Person;
import models.PersonStore;

/**
 *
 * @author Ravindra
 */

public class PersonCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonCreatePanel
     */
    PersonStore personStore;
    HouseStore houseStore;
    models.SystemAdmin systemAdmin;
    CommunityStore communityStore;
    
    public PersonCreatePanel(PersonStore personStore, HouseStore houseStore, models.SystemAdmin systemAdmin, CommunityStore communityStore) {
        initComponents();
        
        this.personStore = personStore;
        this.houseStore = houseStore;
        this.systemAdmin = systemAdmin;
        this.communityStore = communityStore;
        
        initCombos();
    }

    private void initCombos() {
        
        ArrayList<String> communities = new ArrayList<>();
        
        for (Community resource : communityStore.getStore()) {
            
            String tempCommunity = String.valueOf(resource.getCommunityId());
            communities.add(tempCommunity);
        }
        
        
        String[] comRoles = new String[communities.size()];
        
        for (int i = 0; i < communities.size(); i++) {
            comRoles[i] = communities.get(i);
        }
        communityCombo.setModel(new DefaultComboBoxModel<>(comRoles));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextPersonAddress = new javax.swing.JTextField();
        TextPersonId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextHouseId = new javax.swing.JTextField();
        TextPersonGender = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextPersonFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextPersonLastName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextPersonDOB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextPersonEmail = new javax.swing.JTextField();
        TextPersonPhoneNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        TextPersonPassword = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        communityCombo = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Person Panel");

        jLabel2.setText("Person ID");

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Gender");

        TextPersonFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPersonFirstNameActionPerformed(evt);
            }
        });
        TextPersonFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextPersonFirstNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextPersonFirstNameKeyReleased(evt);
            }
        });

        jLabel6.setText("Date of Birth");

        TextPersonLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextPersonLastNameKeyPressed(evt);
            }
        });

        jLabel7.setText("Email");

        jLabel8.setText("Phone Number");

        jLabel9.setText("Address");

        jLabel10.setText("House ID");

        TextPersonPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextPersonPhoneNumberKeyReleased(evt);
            }
        });

        jLabel11.setText("Password");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel12.setText("Community ");

        communityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSubmit)
                    .addComponent(TextPersonId)
                    .addComponent(TextPersonFirstName)
                    .addComponent(TextPersonLastName)
                    .addComponent(TextPersonDOB)
                    .addComponent(TextPersonEmail)
                    .addComponent(TextPersonPhoneNumber)
                    .addComponent(TextPersonAddress)
                    .addComponent(TextHouseId)
                    .addComponent(TextPersonGender, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(TextPersonPassword)
                    .addComponent(communityCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPersonId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPersonFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPersonLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPersonGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPersonDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPersonEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPersonPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPersonAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(communityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextHouseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPersonPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
       Person resource = personStore.addNewResource(); 
       
       resource.setPid(Integer.parseInt(TextPersonId.getText()));
       resource.setHouseId(Integer.parseInt(TextHouseId.getText()));
        
       resource.setAddress(TextPersonAddress.getText());
       resource.setDOB(TextPersonDOB.getText());
       resource.setEmail(TextPersonEmail.getText());
       resource.setFirstName(TextPersonFirstName.getText());
       resource.setLastName(TextPersonLastName.getText());
       resource.setGender(TextPersonGender.getText());
       resource.setPhone(TextPersonPhoneNumber.getText());
       resource.setPassword(TextPersonPassword.getText());
       
       String Email;
        
        
        if(TextPersonEmail.getText().contains("@") && TextPersonEmail.getText().endsWith(".com")){
                Email = TextPersonEmail.getText();
             }
             else{
                 JOptionPane.showMessageDialog(null, "Invalid Email");
            return;
}
       
       
       JOptionPane.showMessageDialog(this,"Successfully added");
        
        TextPersonId.setText("");
        TextHouseId.setText("");
        TextPersonAddress.setText("");
        TextPersonDOB.setText("");
        TextPersonEmail.setText("");
        TextPersonFirstName.setText("");
        TextPersonLastName.setText("");
        TextPersonGender.setText("");
        TextPersonPhoneNumber.setText("");
        TextPersonPassword.setText("");
       
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void communityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communityComboActionPerformed

    private void TextPersonPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPersonPhoneNumberKeyReleased
        // TODO add your handling code here:
        String PhoneNum = TextPersonPhoneNumber.getText();
        int len  = PhoneNum.length();
        char h = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(len<10)
            {
                TextPersonPhoneNumber.setEditable(true);
            }
            else
            {
                TextPersonPhoneNumber.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
             {
                TextPersonPhoneNumber.setEditable(true);
            }
            else
            {
                TextPersonPhoneNumber.setEditable(false);
            }
        }
        if(PhoneNum.matches("^[0-9]*$") && PhoneNum.length()==9)
        {
            TextPersonPhoneNumber.setBackground(Color.GREEN);
          
        }
        else
              TextPersonPhoneNumber.setBackground(Color.red);
        
        
        
        
    }//GEN-LAST:event_TextPersonPhoneNumberKeyReleased

    private void TextPersonFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPersonFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPersonFirstNameActionPerformed

    private void TextPersonFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPersonFirstNameKeyReleased
        // TODO add your handling code here:
   
    }//GEN-LAST:event_TextPersonFirstNameKeyReleased

    private void TextPersonFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPersonFirstNameKeyPressed
        // TODO add your handling code here:
         char C = evt.getKeyChar();
        if (Character.isLetter(C)|| Character.isWhitespace(C) || Character.isISOControl(C)){
        
            TextPersonFirstName.setEditable(true);
        
        }
        
        else{
        
            TextPersonFirstName.setEditable(true);
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Name");
  
}
    
    }//GEN-LAST:event_TextPersonFirstNameKeyPressed

    private void TextPersonLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPersonLastNameKeyPressed
        // TODO add your handling code here:
        char C = evt.getKeyChar();
        if (Character.isLetter(C)|| Character.isWhitespace(C) || Character.isISOControl(C)){
        
            TextPersonLastName.setEditable(true);
        
        }
        
        else{
        
            TextPersonLastName.setEditable(true);
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Name");
  
}
        
    }//GEN-LAST:event_TextPersonLastNameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextHouseId;
    private javax.swing.JTextField TextPersonAddress;
    private javax.swing.JTextField TextPersonDOB;
    private javax.swing.JTextField TextPersonEmail;
    private javax.swing.JTextField TextPersonFirstName;
    private javax.swing.JTextField TextPersonGender;
    private javax.swing.JTextField TextPersonId;
    private javax.swing.JTextField TextPersonLastName;
    private javax.swing.JPasswordField TextPersonPassword;
    private javax.swing.JTextField TextPersonPhoneNumber;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> communityCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
